# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps: 
- script: |
    echo "Replacing BUILDNUM with $(Build.BuildNumber) in k8s/netapp.yaml"
    pwd
    cat k8s/netapp.yaml | sed s/BUILDNUM/$(Build.BuildNumber)/g > k8s/netapp.yaml
    cat k8s/netapp.yaml
    echo "Replaced it"
  displayName: 'Replace version in k8s yaml'
- task: Docker@2
  inputs:
    containerRegistry: 'robrich-acr'
    repository: 'dotnet'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      v-$(Build.BuildNumber)
      latest
- task: CopyFiles@2
  inputs:
    SourceFolder: 'k8s'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
