apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: net-app 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: net-app 
    spec:
      containers:
        - name: net-app 
          image: robrich.azurecr.io/net-app 
          ports:
          - containerPort: 80