apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-app
  template:
    metadata:
      labels:
        app: net-app
        version: BUILDNUM
    spec:
      containers:
      - name: net-app
        image: robrich.azurecr.io/dotnet:BUILDNUM
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: net-app
spec:
  type: NodePort
  selector:
    app: net-app
  ports:
  - port: 80
    targetPort: 80
